name: Avaframe_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.0=py311haa95532_0
  - attrs=25.4.0=pyh71513ae_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.82.0=h59b6b97_2
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.6.15=h4c7d964_0
  - cairo=1.16.0=h85cdd14_6
  - certifi=2025.6.15=py311haa95532_0
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h39d44d4_0
  - click=8.3.0=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=py311haa95532_0
  - contourpy=1.3.2=py311h3257749_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - fiona=1.9.1=py311ha4db88c_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.58.4=py311h5082efb_0
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=hd7a5696_0
  - gdal=3.6.2=py311hc82fbf4_9
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=h4545760_3
  - giflib=5.2.2=h64bf75a_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - imagecodecs=2024.9.22=py311hacb3832_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipython=9.1.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.9=py311h275cad7_1
  - krb5=1.20.1=h5b6d351_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libaec=1.1.4=h20038f6_0
  - libavif=1.3.0=hf2698fe_0
  - libavif16=1.3.0=hf2698fe_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libclang13=14.0.6=default_h8e68704_2
  - libcurl=8.12.1=h9da9810_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=he0cae08_9
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libkml=1.3.0=h63940dd_7
  - liblapack=3.9.0=12_h13b7882_netlib
  - libnetcdf=4.8.1=h6685c40_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libspatialite=5.1.0=h6715bb4_2
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=h44ae7cf_1
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libxslt=1.1.41=h0739af5_0
  - libzip=1.8.0=h289538f_1
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.10.1=py311h8f1b1e4_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - minizip=4.0.3=hb68bac4_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - msys2-conda-epoch=20160418=1
  - munch=4.0.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.1=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=py311haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h2bbff1b_1
  - poppler=24.09.0=h6558a74_1
  - poppler-data=0.4.11=haa95532_1
  - proj=9.3.1=ha107b6e_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyaml=25.5.0=pyhe01879c_0
  - pygments=2.19.1=py311haa95532_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.7.2=py311h2e8c42f_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pywavelets=1.8.0=py311h0a17f05_0
  - pyyaml=6.0.2=py311h5082efb_2
  - qhull=2020.2=h59b6b97_2
  - qtbase=6.7.3=h0804d20_0
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtshadertools=6.7.3=h5da7b33_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebengine=6.7.2=h601c93c_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - rasterio=1.4.3=py311he5c4563_0
  - rasterstats=0.20.0=py311haa95532_0
  - rav1e=0.7.1=ha073cba_3
  - scikit-image=0.25.2=py311hcf9f919_0
  - scikit-learn=1.7.0=py311hdcb8d17_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_0
  - scipy=1.16.0=py311h0e21e1b_0
  - setuptools=78.1.1=py311haa95532_0
  - shapely=2.0.6=py311hba19cfc_0
  - simplejson=3.19.2=py311h827c3e9_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=3.0.2=he0c23c2_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2024.12.12=pyhd8ed1ab_0
  - tiledb=2.3.3=hd8964de_3
  - tk=8.6.14=h5e9d12e_1
  - traitlets=5.14.3=py311haa95532_0
  - typing_extensions=4.12.2=py311haa95532_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py311he736701_0
  - uriparser=0.9.8=h1a0bd13_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_26
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - wcwidth=0.2.13=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - xerces-c=3.2.4=hd77b12b_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h8ffe710_2
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstd=1.5.6=h8880b57_0
